In [1]:
import numpy as np
import time 

In [2]:
# HOW TO CREATE N-DIMENSIONAL ARRAY 
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# EXECUTION PERFORMANCE [PYTHON LIST VS NUMPY ARRAY]

size = 1000000
# PYTHON LIST 
py_list = list(range(size))
start = time.time()
sq = [x**2 for x in py_list]

end = time.time()
print(f"time taken by python list{end-start}")

#NUMPY ARRAY 
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2  # Vectorization 

end = time.time()
print(f"time taken by numpy array {end-start}")


time taken by python list0.10708785057067871
time taken by numpy array 0.0032639503479003906


In [4]:
#HOW TO CREATE NP-ARRAY

arr_2 = np.array([1,3,4,5,"pro"])
print(arr_2)
print(type(arr_2))
print(arr_2.shape)

# CREATING 2-D ARRAYS

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(type(arr2d))
print(arr2d.shape)

['1' '3' '4' '5' 'pro']
<class 'numpy.ndarray'>
(5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)


In [5]:
arry = np.zeros((2,3) , dtype = "int64") #prefill
print(arry)

arry_1 = np.ones((5,)) #prefill 
print(arry_1)

arry_2 = np.full((3,4), 100) #prefill 
print(arry_2 , arry_2.shape)

arry_3 = np.eye(3) # identity elements 
print(arry_3)

arry_4 = np.arange(1,10,2) # range elements
print(arry_4 ,arry_4.dtype) 

arry_5 = np.linspace(1,100,3) # evenely spaced array
print(arry_5 , arry_5.shape)

[[0 0 0]
 [0 0 0]]
[1. 1. 1. 1. 1.]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9] int64
[  1.   50.5 100. ] (3,)


In [6]:
# PROPERTIES OF ARRAYS 
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape) # shape of array  [m x n]=> row x columns
print(arr.size) # total elements
print(arr.dtype)
print(arr.ndim)

(2, 3)
6
int64
2


In [7]:
#Operation on numpy arrays 
#1. RESHAPING ARRAYS 

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

reshaped_arr = arr.reshape(3,2)
print(reshaped_arr , reshaped_arr.shape)

flattened_arr = arr.flatten()#2d to 1d array 
print(flattened_arr , flattened_arr.shape)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [8]:
#2 . INDEXING [1D , 2D , FANCY , BOOLEAN ]
# INDEXING ON 1D ARRAY 
arr  = np.array([1,2,3,4,5,6])
print(arr[0]) #1
print(arr[3]) #4

print("now see how to do indexing on 2d arrays")
# INDEXING ON 2D ARRAY 
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d[1][1])
print(arr2d[0][1])

#FANCY INDEXING 
arr  = np.array([1,2,3,4,5,6])
idx = [0,1,3]
print(arr[idx])

# BOOLEAN INDEXING 
arr = np.array([1,2,3,4,5,6])
print(arr[arr>2])
print(arr[arr%2 == 0])
print(arr[arr%2 != 0])

1
4
now see how to do indexing on 2d arrays
5
2
[1 2 4]
[3 4 5 6]
[2 4 6]
[1 3 5]


In [9]:
#SLICING IN ARRAYS 
arr = np.array([1,2,3,4,5,6])
print(arr[1:4])
print(arr[:])
print(arr[:5])
print(arr[::2])

[2 3 4]
[1 2 3 4 5 6]
[1 2 3 4 5]
[1 3 5]


In [10]:
arr1 = np.array([3+5j])
arr2 = np.array([2+3j])

print(arr1 ,arr1.dtype)
print(arr2 ,arr2.dtype)
print(arr1 + arr2)
print(arr1 - arr2)

arr = np.array(["prime" , {1,2,3} ,3.14])
print(arr , arr.dtype)

[3.+5.j] complex128
[2.+3.j] complex128
[5.+8.j]
[1.+2.j]
['prime' {1, 2, 3} 3.14] object


In [11]:
#3D ARRAY
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D)
print(arr3D.shape)
# indexing 
print(arr3D[1,1,0])
#slicing
print(arr3D[:,0,:]) #first row from both layers
print(arr3D[:,:,0])#first col from both layers 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [12]:
#VECTORIZATION
arr = np.array([1,2,3,4,5,6])
print(arr ** 2)
print(arr + 10) 

# BROADCASTING
arr = np.array([1,2,3,4,5,6])
print(arr + 5)
arr2 = np.array([[1,2,3,4,5,6] ,[1,2,3,4,5,6]])
print(arr + arr2)

[ 1  4  9 16 25 36]
[11 12 13 14 15 16]
[ 6  7  8  9 10 11]
[[ 2  4  6  8 10 12]
 [ 2  4  6  8 10 12]]


In [13]:
#VECTORIZATION NORMALIZATION 

arr = np.array([1,2,3,4,5,6])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


In [14]:
#MATHEMATICAL FUNCTION 
#1 aggregation functions 
arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))#return index of minumum value
print(np.argmax(arr))#return index of maximum value
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0
